name: CI speedcheck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies (Ubuntu)
        continue-on-error: true
        run: sudo apt-get update
          sudo apt-get install python3-pip
        if: matrix.os == 'ubuntu-latest'
      - name: Test package
        run: |
          python3 setup.py install
          playwright install
          speedcheck -h
          speedcheck run --type mlab
          speedcheck run --type cloudflare
